# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: "Ascend"    # choices in ("Ascend", "CPU", "GPU")
need_modelarts_dataset_unzip: True
modelarts_dataset_unzip_name: "face_quality_dataset"

# ==============================================================================
# options
task: 'face_qa'

# dataset related
per_batch_size: 256 # if run 1p
#per_batch_size: 32 # if run 8p

# network structure related
steps_per_epoch: 0
loss_scale: 1024

# optimizer related
lr: 0.02
lr_scale: 1
lr_epochs: '10, 20, 30'
weight_decay: 0.0005
momentum: 0.9
max_epoch: 40
warmup_epochs: 0
pretrained: ''    # change to your own pretrained ckpt
ckpt_dir: ''

# logging related
log_interval: 10
ckpt_path: './output'
ckpt_interval: 500

# train option
is_distributed: 0
train_label_file: ''    # change to your own train data path

# eval option
eval_dir: ''    # change to your own eval data path

# export option
batch_size: 8
file_name: 'FaceQualityAssessment'
file_format: 'MINDIR'  # ['AIR', 'MINDIR']

---

# Help description for each configuration
is_distributed: "if multi device"
train_label_file: "image label list file, e.g. /home/label.txt"
pretrained: "pretrained model to load"
device_target: "device target, choices in ['Ascend', 'GPU', 'CPU']"
eval_dir: "eval image dir, e.g. /home/test"
batch_size: "batch size for export"
file_name: "output file name"
file_format: "file format, choices in ['AIR', 'ONNX', 'MINDIR']"