# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: True
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
data_path: "/cache/data/AddProb"
train_data_path: "/cache/data/AddProb/train"
test_data_path: "/cache/data/AddProb/test"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: Ascend
enable_profiling: False

ckpt_path: './checkpoint_path/'
ckpt_file: '/cache/checkpoint_path/checkpoint_tcn-30_937.ckpt'
# ==============================================================================
# Training options
channel_size: 2
num_classes: 1
lr: 0.004
epoch_size: 25
epoch_change: 15
batch_train: 32
batch_test: 1000
dropout: 1.0
kernel_size: 8
level: 8
nhid: 24
save_checkpoint_steps: 15000
keep_checkpoint_max: 20
N_train: 50000
N_test: 1000
seq_length: 600
device_id: 0
weight_decay: 0.0
file_name: "TCN_forAddingProblem"
file_format: "MINDIR"

model_name: TCN
dataset_name: 'adding_problem'
sink_size: -1
dataset_sink_mode: True
save_checkpoint: True

# acc calculation
result_path: ''
img_path: ''

# preprocess  saved
preprocess_file: './preprocess_Result'
---
# Config description for each option
enable_modelarts: 'Whether training on modelarts, default: False'
data_url: 'Dataset url for obs'
train_url: 'Training output url for obs'
data_path: 'Dataset path for local'
output_path: 'Training output path for local'

device_target: 'Target device type'
enable_profiling: 'Whether enable profiling while training, default: False'
file_name: 'output file name.'
file_format: 'file format'
result_path: "result files path."
---
device_target: 'Ascend'
file_format: 'MINDIR'

