dataset: "ImageNet"
data_path: ""
platform: "GPU"
distributed: False
resume: ""
checkpoint: ""


random_seed: 1
resize_value: 240

size: [240, 240]
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

model: "efficientnet_b1"
drop: 0.2
drop_connect: 0.2
opt_eps: 0.001
lr: 0.064
batch_size: 64
decay_epochs: 2.4
warmup_epochs: 5
decay_rate: 0.97
weight_decay: 0.00001
epochs: 600
workers: 8
amp_level: "O0"
opt: "rmsprop"
num_classes: 1000
# Type of global pool "avg" "max" "avgmax" "avgmaxc"
gp: "avg"
momentum: 0.9
warmup_lr_init: 0.0001
smoothing: 0.1
# Use Tensorflow BatchNorm defaults for models that support it
bn_tf: False
save_checkpoint: True
keep_checkpoint_max: 10
loss_scale: 1024
resume_start_epoch: 0

width: 224
height: 224
ckpt_file: ""
file_name: "efficientnet"
file_format: "MINDIR" # ["AIR", "ONNX", "MINDIR"]
device_target: "GPU" # ["GPU", "CPU"]