dataset_type: "ucf101"  # or "kinetics400"
target_size: 224
short_size: 256
class_num: 101  # set 400 for kinetics of 101 for ucf
avgpool_kernel_size: 4  # set 7 for kinetics or 4 for ucf

T: 7  # segnum
N: 5  # seglen
image_mean: [0.485, 0.456, 0.406]
image_std: [0.229, 0.224, 0.225]

dataset_path: ""
run_distribute: False
resume: ""
device_num: 1
rank_id: 0
profile: False
dataset_sink_mode: True

# train
batch_size: 16
steps_size: 0
num_epochs: 90
mode: "GRAPH"
target: ""
device_id: 0
workers: 2
save_checkpoint: True
eval_per_epoch: 10
parameter_server: True
keep_checkpoint_max: 5
save_checkpoint_epochs: 1
save_best_ckpt: True
eval_start_epoch: 40
run_eval: False
eval_interval: 10
pre_res50: ""

# opt
momentum: 0.9
lr: 0.001
lr_decay_rate: 40
gamma: 0.1
weight_decay: 0.0001

# val
checkpoint_path: "./ckpt"
val_data_dir: ""
summary_dir: "./summary"

# model_Art
run_online: False
data_url: ""
local_data_url: ""
pre_res50_art_load_path: ""
best_acc_art_load_path: ""
pre_url: ""
load_path: ""
local_train_list: ""
local_val_list: ""
train_url: ""
output_path: ""
