# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
run_distribute: False
enable_profiling: False
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path/"
device_target: "Ascend"
checkpoint_path: "./checkpoint/"
checkpoint_file_path: ""

# ==============================================================================
# Training options
task: "train"
epochs: 20
batch_size: 192
dtype: float32 #only support float16 and float32
compute_type: float16 #only support float16 and float32
pre_train_dataset: ""
fine_tune_dataset: ""
test_dataset: ""
valid_dataset: ""
dataset_sink_mode: false
dataset_sink_step: 100
random_seed: 100
save_graphs: false
seq_length: 64
vocab_size: 45744
hidden_size: 1024
num_hidden_layers: 6
num_attention_heads: 8
intermediate_size: 4096
hidden_act: "relu"
hidden_dropout_prob: 0.2
attention_dropout_prob: 0.2
max_position_embeddings: 64
initializer_range: 0.02
label_smoothing: 0.1
beam_width: 4
length_penalty_weight: 1.0
max_decode_length: 64
loss_scale_mode: "dynamic"
init_loss_scale: 65536
loss_scale_factor: 2
scale_window: 200
optimizer: "adam"
lr: 0.0001
lr_scheduler: "poly"
poly_lr_scheduler_power: 0.5
decay_steps: 10000
decay_start_step: 12000
warmup_steps: 4000
min_lr: 0.000001
existed_ckpt: ""
save_ckpt_steps: 2500
keep_ckpt_max: 50
ckpt_prefix: "ckpt"
metric: "rouge"
vocab: ""
output: ""

# Export options
device_id: 0
ckpt_file: ""
file_name: "mass"
file_format: "MINDIR"
vocab_file: ""
result_path: "./preprocess_Result/"
source_id_folder: "./preprocess_Result/00_source_eos_ids"
target_id_folder: "./preprocess_Result/target_eos_ids"
result_dir: "./result_Files"

---
# Help description for each configuration
enable_modelarts: "Whether training on modelarts, default: False"
data_url: "Dataset url for obs"
train_url: "Training output url for obs"
checkpoint_url: "The location of checkpoint for obs"
data_path: "Dataset path for local"
output_path: "Training output path for local"
load_path: "The location of checkpoint for obs"
device_target: "Target device type, available: [Ascend, GPU, CPU]"
enable_profiling: "Whether enable profiling while training, default: False"
num_classes: "Class for dataset"
batch_size: "Batch size for training and evaluation"
epoch_size: "Total training epochs."
keep_checkpoint_max: "keep the last keep_checkpoint_max checkpoint"
checkpoint_path: "The location of the checkpoint file."
checkpoint_file_path: "The location of the checkpoint file."
