# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: Ascend
enable_profiling: False

# ==============================================================================
# Training options
epoch_size: 30
save_checkpoint: True
keep_checkpoint_max: 10
save_checkpoint_epochs: 5
save_checkpoint_steps: -1
ckpt_path: ""
lr: 0.1
momentum: 0.9
batch_size: 32
buffer_size: 1000
dataset_name: imagenet

# Model Description
model_name: lenet_running_8p
image_height: 32
image_width: 32
num_classes: 10


---
# Config description for each option
enable_modelarts: 'Whether training on modelarts, default: False'
data_url: 'Dataset url for obs'
train_url: 'Training output url for obs'
data_path: 'Dataset path for local'
output_path: 'Training output path for local'

device_target: 'Target device type'
enable_profiling: 'Whether enable profiling while training, default: False'


---
device_target: ['Ascend', 'GPU', 'CPU']
