# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
data_path: "dataset"
output_path: "results"
load_path: "/cache/checkpoint_path"
device_target: "Ascend"
enable_profiling: False

# ==============================================================================
# Training options
phase: train
light: False
distributed: False
dataset: selfie2anime
epoch: 100
batch_size: 1
print_freq: 1
save_freq: 10
decay_flag: True
decay_epoch: 50
resume: False
save_graphs: False
graph_path: graph_path
compute_metrics: False
inception_ckpt_path: '/path/to/inception_for_metrics.ckpt'

loss_scale: 1024.0
lr: 0.0001
weight_decay: 0.0001
adv_weight: 1
cycle_weight: 10
identity_weight: 10
cam_weight: 1000

ch: 64
n_res: 4
n_dis: 6
img_size: 256
img_ch: 3
use_global_norm: True

device_id: "4"
genA2B_ckpt: './results/selfie2anime_genA2B_params_latest.ckpt'
MINDIR_outdir: './mindir_result'

export_file_format: "MINDIR"
bifile_inputdir: './bifile_in'
bifile_outputdir: './bifile_out'
eval_outputdir: './infer_output_img'

---
# Config description for each option
enable_modelarts: 'Whether training on modelarts, default: False'
data_url: 'Dataset url for obs'
train_url: 'Training output url for obs'
data_path: 'Dataset path for local'
output_path: 'Training output path for local'

device_target: 'Target device type'
enable_profiling: 'Whether enable profiling while training, default: False'


---
device_target: ['Ascend', 'GPU', 'CPU']
