# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"

# ==============================================================================
# options

# Context options
device_target: "GPU"
device_id: 0
is_train_distributed: False

# Model options
model_name: "MIMO-UNet"

# Dataset options
dataset_root: "/path/to/dataset/"
train_batch_size: 4

# Logging options
ckpt_save_frequency: 100
ckpt_save_directory: "saving/ckpt/directory"
img_save_directory: ""

# Training options
learning_rate: 0.0001
num_worker: 8
epochs_num: 3000
train_use_data_sink: False

# Evaluation and export options
ckpt_file: "/path/to/trained/checkpoint.ckpt"
eval_use_data_sink: False
eval_batch_size: 1
export_batch_size: 1
export_file_name: "MIMO-UNet"
export_file_format: "MINDIR"
export_device_target: "GPU"

---

# Help description for each configuration

# Context options
device_target: "Device type which will be used for graph computations"
device_id: "Id of device which will be used for graph computations"
is_train_distributed: "Whether the training process is distributed among several devices"

# Model options
model_name: "Name of the model"

# Dataset options
dataset_root: "Path to the dataset root, containing train and test folders"
train_batch_size: "The batch size to be used for training"

# Logging options
ckpt_save_frequency: "Specifies the number epoch which must pass before saving a single checkpoint."
ckpt_save_directory: "Output directory, where the data from the train process will be stored."
img_save_directory: "Output directory, where the data from the validation process will be stored."

# Training options
learning_rate: "Learning rate"
epochs_num: "Number of the epochs"
train_use_data_sink: "Use data sink mode during the model training."

# Evaluation and export options
ckpt_file: "Path to the checkpoint containing the weights of the trained model."
eval_use_data_sink: "Use data sink mode during the model evaluation."
export_batch_size: "Batch size used for the exported model"
export_file_name: "Exported model file name"
export_file_format: "Format of the exported model"
export_device_target: "Device type which will be used for export"
