# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"

# ==============================================================================
# options
# if run on modelarts, the data and pre_ckpt dir should be in the form '/cache/.../...'
train_state: "attn"

seed: 0
batch_size: 32
start_iter: 1
max_iters: 500000
image_size: 321

initial_lr: 0.01
attention_loss_weight: 1.0

traindata_path: "/mass_data/gldv2_dataset/mindrecord/train.mindrecord000"
keep_checkpoint_max: 1
imagenet_checkpoint: "./resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5"
checkpoint_path: ""
save_ckpt: "./ckpt/"
save_ckpt_step: 2000
need_summary: False
save_summary: "./summary_test"
need_profile: False

---

# Help description for each configuration
train_state: "Training mode, choices: 'tuning', 'attn' "
enable_modelarts: "Whether training on modelarts, default: False"
data_url: "Url for modelarts"
train_url: "Url for modelarts"
data_path: "The location of the input data."
output_path: "The location of the output file."
