# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path/"
device_target: 'Ascend'
enable_profiling: False

# ==============================================================================
# Common options
net: "densenet100"
dataset: "cifar10"
is_distributed: 0
rank: 0
group_size: 1

# ==============================================================================
# Training options
train_data_dir: ""
train_pretrained: ""
model_train_url: ""
image_size: "32, 32"
num_classes: 10
lr: 0.1
lr_scheduler: "exponential"
lr_epochs: "150, 225, 300"
lr_gamma: 0.1
eta_min: 0
T_max: 120
max_epoch: 300
per_batch_size: 64
warmup_epochs: 0
weight_decay: 0.0001
momentum: 0.9
is_dynamic_loss_scale: 0
loss_scale: 1024
label_smooth: 0
label_smooth_factor: 0.1
log_interval: 100
ckpt_interval: 3124
save_ckpt_path: "./"
is_save_on_master: 1

# Eval options
eval_data_dir: ""
backbone: "resnet50"
ckpt_files: ""
log_path: ""
eval_url: ""

# export options
device_id: 0
batch_size: 32
file_name: "densenet"
file_format: "MINDIR"

---
# Help description for each configuration
enable_modelarts: "if enable_modelarts"
data_url: ""
train_url: ""
checkpoint_url: ""
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path/"
device_target: 'Ascend'
enable_profiling: False
net: "Densenet Model, densenet100 or densenet121"
dataset: "Dataset, either cifar10 or imagenet"
is_distributed: "if multi device"
train_data_dir: "train url"
train_pretrained: "model_path, local pretrained model to load"
model_train_url: "model train url"
image_size: "input image sizes"
num_classes: "num_classes"
lr: "lr"
lr_scheduler: "consine_annealing"
lr_epochs: "lr epochs"
ckpt_path: "train ckpt save path"
log_path: "path to save log"
ckpt_files: "fully path of pretrained model to load If it is a direction, it will test all ckpt"
rank: "local rank of distributed"
group size: "world size of distributed"
backbone: "backbone"
device_id: "Device id"
file_name: "output file name"
file_format: "file format choices [AIR MINDIR ONNX]"
