# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
# Url for modelarts
enable_modelarts: False
data_url: ""
train_url: ""
checkpoint_url: ""
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
need_modelarts_dataset_unzip: True
modelarts_dataset_unzip_name: "ucf101"
# ==============================================================================
# Train and val options
dataset: "ucf101"
modality: "RGB"
train_list: "data/ucf101_rgb_train_split_1.txt"
val_list: "data/ucf101_rgb_val_split_1.txt"
arch: "ECO"
num_segments: 4
consensus_type: "identity"
dropout: 0.7
loss_type: "nll"
epochs: 40
batch-size: 16
lr: 0.001
momentum: 0.9
no_partialbn: True
nesterov: True
weight_decay: 0.0005
num_saturate: 5
workers: 1
run_distribute: False
resume: "ms_model_kinetics_checkpoint0720.ckpt"
device_target: Ascend
device_id: 0
rgb_prefix: "img_"
eval_freq: 1
evaluate: False
# ==============================================================================
# export
checkpoint_path: "ucf101bestacc.ckpt"
file_format: "MINDIR"
file_name: "ecolite"
