# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unlesee you know exactly what you are doing)
enable_modelarts: False
# url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: "Ascend"
enable_profiling: False

# ======================================================================================
# common options
num_classes: 1000 
device_id: 0
rank: 0
group_size: 1

# ======================================================================================
# Training options
epoch_size: 240  
keep_checkpoint_max: 20
save_ckpt_path: "./"
save_checkpoint_epochs: 1
save_checkpoint: True
save_only_device_0: True

amp_level: "O3"
is_distributed: False
dataset_path: "../imagenet"
resume: ""
resume_epoch: 1
random_seed: 1

work_nums: 8
cutout: True
cutout_length: 56

# drop_remainder , True for GPU, False for Ascend
drop_remainder: False

# TLU method
method: 2

# image size
enlarged_image_size: 256
final_image_size: 224

# Dataset config
train_batch_size: 32
val_batch_size: 125

#learning rate config
lr_init: 0.025

#optimization config
weight_decay: 0.0001
momentum: 0.9

#mode config
use_pynative_mode: False
# ======================================================================================
# Eval options
checkpoint: ""
enable_checkpoint_dir: False
checkpoint_dir: ""

# ======================================================================================
# export options
file_name: "resnetv2_50_frn"
file_format: "MINDIR"

---
# Help description for each configuration
enable_modelarts: "Whether training on modelarts default: False"
data_url: "Url for modelarts"
train_url: "Url for modelarts"
data_path: "The location of input data"
output_pah: "The location of the output file"
device_target: "device id of GPU or Ascend. (Default: Ascend)"
enable_profiling: "Whether enable profiling while training default: False"
is_distributed: "distributed training"
resume: "resume training with existed checkpoint"
device_id: "device id"
file_name: "output file name"
file_format: "file format choices [AIR MINDIR ONNX]"
