general:
    backend: mindspore

pipeline: [eval]

eval:
    pipe_step:
        type: TrainPipeStep
        models_folder: ~
    dataset:
        type: Imagenet
        common:
            data_path: "/cache/datasets/ILSVRC/Data/CLS-LOC"
            batch_size: 64
            n_class: 1000
    trainer:
        with_train: False
        type: Trainer
        epochs: 160
        optimizer:
            type: SGD
            params:
                lr: 0.1  # 0.001 for mindspore
                momentum: 0.9
                weight_decay: 0.0001  # 0.01 for mindspore
        lr_scheduler:
            type: MultiStepLR
            params:
                milestones: [60, 120]
                gamma: 0.5
        loss:
            type: CrossEntropyLoss
