# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: "Ascend"
need_modelarts_dataset_unzip: True
modelarts_dataset_unzip_name: "ImageNet"

# ==============================================================================
# options
num_classes: 1000
lr: 0.04
lr_init: 0.01
lr_max: 0.1
lr_epochs: '30,60,90,120'
lr_scheduler: 'cosine_annealing'
warmup_epochs: 0
batch_size: 64
max_epoch: 90
momentum: 0.9
weight_decay: 0.0001 # 1e-4
loss_scale: 1024
label_smooth: 1
label_smooth_factor: 0.1
buffer_size: 10
image_size: [224,224]
pad_mode: 'pad'
has_bias: False
batch_norm: False
keep_checkpoint_max: 10
initialize_mode: "KaimingNormal"
has_dropout: True

# train option
dataset: "imagenet2012"
data_dir: ""
pre_trained: ""
lr_gamma: 0.1
eta_min: 0.0
T_max: 90
log_interval: 100
ckpt_path: "outputs/"
ckpt_interval: 5
is_save_on_master: 1
is_distributed: 0

# eval options
per_batch_size: 32
graph_ckpt: 1
log_path: "outputs/"

# postprocess options
result_dir: ""
label_dir: ""
dataset_name: "imagenet2012"

# preprocess options
result_path: "./preprocess_Result/"

# export options
ckpt_file: ""
file_name: "vgg16"
file_format: "MINDIR"

---

# Help description for each configuration
device_target: "device where the code will be implemented."
dataset: "choices in ['cifar10', 'imagenet2012']"
data_dir: "data dir"
pre_trained: "model_path, local pretrained model to load"
lr_gamma: "decrease lr by a factor of exponential lr_scheduler"
eta_min: "eta_min in cosine_annealing scheduler"
T_max: "T-max in cosine_annealing scheduler"
log_interval: "logging interval"
ckpt_path: "checkpoint save location"
ckpt_interval: "ckpt_interval"
is_save_on_master: "save ckpt on master or all rank"
is_distributed: "if multi device"
pad_mode: "choices in ['same', 'pad']"

# eval options
per_batch_size: "batch size for per npu"
graph_ckpt: "graph ckpt or feed ckpt"
log_path: "path to save log"

# postprocess options
result_dir: "result files path."
label_dir: "image file path."
dataset_name: "choices in ['cifar10', 'imagenet2012']"

# preprocess options
result_path: "result path"

# export options
ckpt_file: "vgg16 ckpt file."
file_name: "vgg16 output file name."
file_format: "file format, choices in ['AIR', 'ONNX', 'MINDIR']"