# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: "Ascend"
need_modelarts_dataset_unzip: False
modelarts_dataset_unzip_name: ""

# ==============================================================================
# options
per_batch_size: 128
dst_h: 112
dst_w: 112
workers: 8
attri_num: 3
classes: '9,2,2'
backbone: 'resnet18'
loss_scale: 1024
flat_dim: 512
fc_dim: 256
lr: 0.009
lr_scale: 1
lr_epochs: [20, 30, 50]
weight_decay: 0.0005
momentum: 0.9
max_epoch: 70
warmup_epochs: 0
log_interval: 10
ckpt_path: './output'
ckpt_max_num: 10

# data_to_mindrecord parameter
eval_dataset_txt_file: 'Your_label_txt_file'
eval_mindrecord_file_name: 'Your_output_path/data_test.mindrecord'
train_dataset_txt_file: 'Your_label_txt_file'
train_mindrecord_file_name: 'Your_output_path/data_train.mindrecord'
train_append_dataset_txt_file: 'Your_label_txt_file'
train_append_mindrecord_file_name: 'Your_previous_output_path/data_train.mindrecord0'

# tran/eval/preprocess option
mindrecord_path: ""
pretrained: ""
local_rank: 0
world_size: 8
model_path: ""
ckpt_dir: ""

# export option
ckpt_file: ""
file_name: "faceattri"
file_format: "MINDIR"

---

# Help description for each configuration
enable_modelarts: "Whether training on modelarts, default: False"
data_url: "Url for modelarts"
train_url: "Url for modelarts"
data_path: "The location of the input data."
output_path: "The location of the output file."
device_target: 'Target device type'
enable_profiling: 'Whether enable profiling while training, default: False'

# tran/eval/preprocess option
mindrecord_path: "dataset path, e.g. /home/data.mindrecord"
pretrained: "pretrained model to load"
local_rank: "current rank to support distributed"
world_size: "current process number to support distributed"
model_path: "pretrained model to load"

# export option
ckpt_file: "pretrained model to load"
file_name: "file name"
file_format: "file format, choices in ['MINDIR', 'AIR']"
