# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: "Ascend"
need_modelarts_dataset_unzip: True
modelarts_dataset_unzip_name: "ImageNet"

# ==============================================================================
# default options
image_size: "224,224"
num_classes: 1000
lr: 0.1
lr_scheduler: "cosine_annealing"
lr_epochs: "30,60,90,120"
lr_gamma: 0.1
eta_min: 0
T_max: 150
max_epoch: 150
warmup_epochs: 5
weight_decay: 0.0001
momentum: 0.9
is_dynamic_loss_scale: 0
loss_scale: 1024
label_smooth: 1
label_smooth_factor: 0.1
ckpt_interval: 1
ckpt_save_max: 10
ckpt_path: "outputs/"
is_save_on_master: 1

data_dir: ""
pretrained: ""
is_distributed: 1
per_batch_size: 64

log_path: "outputs/"

# export options
export_batch_size: 1
ckpt_file: ""
file_name: "cspdarknet53"
file_format: "MINDIR"
width: 224
height: 224

---

# Help description for each configuration
enable_modelarts: "Whether training on modelarts, default: False"
data_url: "Url for modelarts"
train_url: "Url for modelarts"
data_path: "The location of the input data."
output_path: "The location of the output file."
device_target: 'Target device type'
graph_ckpt: "graph ckpt or feed ckpt"

# export options
export_batch_size: "batch size for export"
ckpt_file: "cspdarknet53 ckpt file"
file_name: "output mindir name."
file_format: "file format, choices in ['AIR', 'ONNX', 'MINDIR']"
width: "input width"
height: "input height"