# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
isModelArts: False
# Url for modelarts
device_target: "Ascend"
device_id: 0
run_distribute: False
train_url: ""
data_url: ""

# ==============================================================================
# Training options
data_path: "./MICCAI_BraTS17_Data_Training/HGG"
mindrecord_path: ""
train_path: "./src/train.txt"
test_path: "./src/test.txt"
ckpt_path: ""
correction: True
dataset_sink_mode: True
model: 'dense24'
use_optimizer: 'SGD'
use_dynamic_lr: True
use_loss_scale: False
use_mindrecord: False
epoch_size: 5
batch_size: 2
num_classes: 5
offset_width: 12
offset_height: 12
offset_channel: 12
width_size: 38
height_size: 38
channel_size: 38
pred_size: 12
lr: 0.005
loss_scale: 128.0
momentum: 0.9
weight_decay: 0.001
warmup_step: 6720
warmup_ratio: 0
keep_checkpoint_max: 5

# Export options
ckpt_file: "./dense24-5_4200.ckpt"
file_name: "dense24"
file_format: "MINDIR"

# 310 infer options
pre_result_path: "./preprocess_Result"
post_result_path: "./result_Files"
image_width: 240
image_height: 240
image_channel: 155

# onnx eval
onnx_path: ""

---
# Help description for each configuration
data_path: "The directory of data."
train_path: "The path of train.txt "
device_target: "Target device type, available: [Ascend, GPU, CPU]"
data_url: "Dataset url for obs"
train_url: "Training output url for obs"
epoch_size: "Total training epochs."
batch_size: "Batch size for training and evaluation"
num_classes: "Class for dataset"
keep_checkpoint_max: "keep the last keep_checkpoint_max checkpoint"
ckpt_path: "The location of the checkpoint file."