# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
device_target: "GPU"
run_distributed: True
device_num: ""
net: "darknet53"
dataset: "imagenet2012"
dataset_path: ""
pre_trained: ""
class_num: 1000
epoch_num: 150
pretrained_epoch_num: 0
batch_size: 256
momentum: 0.9
loss_scale: 1024
weight_decay: 0.0001
use_label_smooth: True
label_smooth_factor: 0.1
lr: 0.1
lr_scheduler: "cosine_annealing"
eta_min: 0
T_max: 150
warmup_epochs: 5
checkpoint_path: ""
save_checkpoint: True
save_checkpoint_epochs: 5
keep_checkpoint_max: 90
save_checkpoint_path: "./"
summary_dir: "./summary_dir"
