net: DBnetPP
backbone:
    initializer: resnet50
    pretrained: True
    backbone_ckpt: "./pretrained/resnet50-19c8e357.ckpt" # If on modelarts, set the name of checkpoint saved in data_url
segdetector:
    in_channels: [256, 512, 1024, 2048]  # R18: [64, 128, 256, 512]
    attention_type: scale_channel_spatial
optimizer:
    lr:
        base_lr: 0.007
eval:
    box_thresh: 0.6

