# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)

# eqn config
eqn_name: "HJBLQ"
total_time: 1.0
dim: 100
num_time_interval: 20

# net config
y_init_range: [0, 1]
num_hiddens: [110, 110]
lr_values: [0.01, 0.01]
lr_boundaries: [1000]
num_iterations: 2000
batch_size: 64
valid_size: 256
logging_frequency: 100

# other config
device_target: "GPU"
log_dir: "./logs"
file_format: "MINDIR"

---

# Help description for each configuration
eqn_name: "Equation function name."
total_time: "The total time of equation function."
dim: "Hidden layer dims."
num_time_interval: "Number of interval times."
y_init_range: "The y_init random initialization range."
num_hiddens: "A list of hidden layer's filter number."
lr_values: "lr_values of piecewise_constant_lr."
lr_boundaries: "lr_boundaries of piecewise_constant_lr."
num_iterations: "Iterations numbers."
batch_size: "batch_size when training."
valid_size: "batch_size when evaluation."
logging_frequency: "logging and evaluation callback frequency."
device_target: "Device where the code will be implemented. Optional values is GPU."
log_dir: "The path of log saving."
file_format: "Export model type."
