# ==============================================================================
# basic parameters
n_color: 3                                                #  color channels of input images
device_target: "Ascend"                                   #  device to run the model ["Ascend", "GPU"]

# Dataset settings
train_path: "/home/data2/egnet/DUTS-TR-10498"             #  training dataset dir;
test_path: "/home/data2/egnet/data200"                    #  testing dataset root;
infer_path: "/home/data2/egnet/data200"                   #  infer dataset root;
infer_image_root: "/home/stu/lrsh/data_crop/SOD/images/"  #  infer dataset image;

# Training settings
base_model: "resnet"                                      #  bone network ["resnet", "vgg"], used when train and eval;
vgg: "/home/EGNet/EGNet/model/vgg16.ckpt"                 #  set pre-trained model
resnet: "/home/EGNet/EGNet/model/resnet50.ckpt"           #  set pre-trained model
is_distributed: False                                     #  set distributed training
epoch: 30                                                 #  epoch
batch_size: 1
n_ave_grad: 10                                            #  step size for gradient accumulation.
num_thread: 4                                             #  thread num for dataset
save_fold: "EGNet"                                        #  root directory for training information
train_save_name: "nnet"
epoch_save: 1
epoch_show: 1
show_every: 10
save_tmp: 200
loss_scale: 1

# Training with checkpoint
pre_trained: ""                                            # checkpoint file 
start_epoch: 1                                             # start epoch for training


# Testing settings
model: "/home/data3/egnet_models/resnet/msp/final_bone_1128_1.ckpt"         #  model for evaluation
test_fold: "result"
test_save_name: "EGNet_"
test_mode: 1
sal_mode: "t" # ['e','t','d','h','p','s']                  #  which dataset to evaluate
test_batch_size: 1                                         # test batch, do not edit now!


# Online training setting
train_online: False
online_train_path: ""
online_pretrained_path: ""
train_url: ""                                                       
pretrained_url: "pretrained"                              #  used when train and eval;

# Online testing setting
eval_online: False
online_eval_path: ""
online_ckpt_path: ""

# Export settings
file_name: "EGNet"
file_format: "MINDIR"
ckpt_file: ""

