dataset:
  path: ./coco
  type: coco
  parallel: 1
  phase: val2014
  ann: person_keypoints  # 'image_info' or 'person_keypoints'
load_ckpt: out/tf2ms.ckpt
coco_only_images_with_people: true

context:
  device_target: GPU
  mode: 1

all_joints: [ [ 0 ], [ 2, 1 ], [ 4, 3 ], [ 6, 5 ], [ 8, 7 ], [ 10, 9 ], [ 12, 11 ], [ 14, 13 ], [ 16, 15 ] ]
all_joints_names: [ "nose", 'eye', 'ear', 'shoulder', 'elbow', 'hand', 'hip', 'knee', 'foot' ]
num_joints: 17

global_scale: 1.0
pos_dist_thresh: 17

location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801

pairwise_predict: true
pairwise_huber_loss: true
pairwise_loss_weight: 0.05
pairwise_stats_fn: out/pairwise_stats.mat
pairwise_model_dir: out/pairwise

intermediate_supervision: true
intermediate_supervision_layer: 12

max_input_size: 650
multi_step:
  - [ 0.005,0.02,0.002,0.0005,0.0002,0.00005 ]
  - [ 10000,450000,750000,1050000,1550000,1800000 ]
display_iters: 20
save_iters: 200000

nms_radius: 5.0
det_min_score: 0.2
use_gt_segm: yes
gt_segm_output: out/predictions_with_segm.json
