dataset:
  path: ./coco
  type: coco
  parallel: 1
  phase: train2014
  ann: person_keypoints  # 'image_info' or 'person_keypoints'

coco_only_images_with_people: true

all_joints: [ [ 0 ], [ 2, 1 ], [ 4, 3 ], [ 6, 5 ], [ 8, 7 ], [ 10, 9 ], [ 12, 11 ], [ 14, 13 ], [ 16, 15 ] ]
all_joints_names: [ "nose", 'eye', 'ear', 'shoulder', 'elbow', 'hand', 'hip', 'knee', 'foot' ]
num_joints: 17
global_scale: 1.0
pos_dist_thresh: 17


location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801

pairwise_predict: no
pairwise_huber_loss: true
pairwise_loss_weight: 0.05
pairwise_stats_fn: out/pairwise_stats.mat

intermediate_supervision: true
intermediate_supervision_layer: 12

max_input_size: 650
