dataset:
  path: out/test_index_dataset.json
  type: mpii_raw
  parallel: 1
  batch_size: 1
  mirror: no
  padding: no
  shuffle: no
  
train: no
output: out/prediction.mat
pck_threshold: 0.5

num_joints: 14
all_joints: [ [ 0, 5 ], [ 1, 4 ], [ 2, 3 ], [ 6, 11 ], [ 7, 10 ], [ 8, 9 ], [ 12 ], [ 13 ] ]
all_joints_names: [ 'ankle', 'knee', 'hip', 'wrist', 'elbow', 'shoulder', 'chin', 'forehead' ]

pos_dist_thresh: 17
global_scale: 0.8452830189

location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801

intermediate_supervision: no
intermediate_supervision_layer: 12

max_input_size: 600
multi_step:
  - [ 0.005,0.02,0.002,0.001 ]
  - [ 10000,430000,730000,1030000 ]

