dataset:
  path: out/train_index_dataset.json
  type: mpii_raw
  parallel: 1
  # need about 13G GPU memory
  batch_size: 16
  mirror: true
  padding: yes
  shuffle: yes
load_ckpt: out/pretrained_resnet101.ckpt
context:
  # GRAPH
  # mode: 0

  # PYNATIVE
  mode: 1
  device_target: GPU

parallel_context:
  parallel_mode: data_parallel

epoch: 25
train: yes

num_joints: 14
all_joints: [ [ 0, 5 ], [ 1, 4 ], [ 2, 3 ], [ 6, 11 ], [ 7, 10 ], [ 8, 9 ], [ 12 ], [ 13 ] ]
all_joints_names: [ 'ankle', 'knee', 'hip', 'wrist', 'elbow', 'shoulder', 'chin', 'forehead' ]

pck_threshold: 2


pos_dist_thresh: 17
global_scale: 0.8452830189

location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801

intermediate_supervision: no
intermediate_supervision_layer: 12
intermediate_supervision_input: 1024

max_input_size: 600
multi_step:
  - [ 0.05,0.2,0.02,0.01 ]
  - [ 500,2700,4600,6500 ]

