dataset:
  path: "./src/mpii/cropped/dataset.json"
  type: mpii_raw
  parallel: 8
  batch_size: 20
  mirror: true
  padding: yes
  shuffle: yes
model_arts:
  IS_MODEL_ARTS : no
  CACHE_INPUT : '/cache/data/'
  CACHE_OUTPUT: '/cache/train_out/'
  GENERAL_RUN_DISTRIBUTE: no
  SAVE_CKPT: yes
  VERSION: 'commit'
under_line:
  DATASET_ROOT : "/data/arttrack/PR/ArtTrack/"
  CKPT_path : '/data/arttrack/PR/ArtTrack/Ascend/ckpt/'
load_ckpt: ./arttrack-1015.ckpt
context:
  mode: 0

  device_target: Ascend
  device_id: 7

parallel_context:
  parallel_mode: data_parallel

epoch: 23
train: yes

num_joints: 14
all_joints: [ [ 0, 5 ], [ 1, 4 ], [ 2, 3 ], [ 6, 11 ], [ 7, 10 ], [ 8, 9 ], [ 12 ], [ 13 ] ]
all_joints_names: [ 'ankle', 'knee', 'hip', 'wrist', 'elbow', 'shoulder', 'chin', 'forehead' ]

pck_threshold: 2


pos_dist_thresh: 17
global_scale: 0.8452830189

location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801

intermediate_supervision: no
intermediate_supervision_layer: 12
intermediate_supervision_input: 1024

max_input_size: 600
multi_step:
multi_step:
  - [ 0.05,0.2,0.02,0.01 ]
  - [ 500,2700,4600,6500 ]
