general:
    backend: mindspore

pipeline: [eval]

eval:
    pipe_step:
        type: TrainPipeStep
        models_folder: ~
    dataset:
        type: DIV2K
        common:
            value_div: 255.0
        train:
            root_HR: /cache/datasets/DIV2K/div2k_train/hr
            root_LR: /cache/datasets/DIV2K/div2k_train/lr
            upscale: 2
            crop: 64    # crop size of lr image
            hflip: true    # flip image horizontally
            vflip: true    # flip image vertically
            rot90: true    # flip image diagonally
            shuffle: true
            num_workers: 2
            batch_size: 16
            pin_memory: false
        test:
            root_HR: /cache/datasets/DIV2K/div2k_valid/hr
            root_LR: /cache/datasets/DIV2K/div2k_valid/lr
            upscale: 2
            crop: 64
            pin_memory: false
    trainer:
        with_train: False
        type: Trainer
        epochs: 400
        optimizer:
            type: Adam
            params:
                lr: 0.0004
        lr_scheduler:
            type: MultiStepLR
            params:
                milestones: [100, 200]
                gamma: 0.5
        loss:
            type: L1Loss
        metric:
            type: PSNR
            params:
                scale: 2
        calc_params_each_epoch: True

    evaluator:
        type: Evaluator
        host_evaluator:
            type: HostEvaluator
            metric:
                type: PSNR
            load_pkl: False
