# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: True
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
data_path: "/cache/data"
output_path: "/cache/ckpt"
load_path: "/cache/checkpoint_path"
# ==============================================================================
# Model
nstack: 2
inp_dim: 256
oup_dim: 16
input_res: 256
output_res: 64
annot_dir: "/cache/data/MPII/annot"
img_dir: "/cache/data/MPII/images"
# Context
context_mode: "GRAPH"
device_target: "Ascend"
# Train
parallel: False
amp_level: "O2"
batch_size: 32
num_epoch: 100
save_checkpoint_epochs: 5
keep_checkpoint_max: 20
loss_log_interval: 1
initial_lr: 0.001
decay_rate: 0.985
decay_epoch: 1
# Test
num_eval: 2958
train_num_eval: 300
ckpt_file: "ckpt-100_695.ckpt"
# Export
file_name: "Hourglass"
file_format: "MINDIR"  # ["AIR", "MINDIR"]
result_path: "../ascend310_infer/preprocess_Result"
out_path: "../ascend310_infer/result_Files"

