# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
run_distribute: False
enable_profiling: False
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path/"
device_target: "GPU"
checkpoint_path: "./checkpoint/"
checkpoint_file_path: ""

# ==============================================================================
# Training options
optimizer: "Momentum"
infer_label: ""
class_num: 1001
batch_size: 256
loss_scale: 1024
momentum: 0.9
weight_decay: 0.0001
epoch_size: 100
start_epoch: 0
pretrain_epoch_size: 0
save_checkpoint: True
save_checkpoint_epochs: 5
keep_checkpoint_max: 10
warmup_epochs: 2
lr_decay_mode: "linear"
use_label_smooth: True
label_smooth_factor: 0.1
lr_init: 0
lr_max: 0.8
lr_end: 0.0
lars_epsilon: 0.0
lars_coefficient: 0.001

net_name: "resnet18"
dataset: "imagenet2012"
device_num: 1
pre_trained: ""
run_eval: False
eval_dataset_path: ""
parameter_server: False
filter_weight: False
save_best_ckpt: True
eval_start_epoch: 40
eval_interval: 1
enable_cache: False
cache_session_id: ""
mode_name: "GRAPH"
boost_mode: "O0"
conv_init: "XavierUniform"
dense_init: "TruncatedNormal"
train_image_size: 224
eval_image_size: 224

# Golden-stick options
comp_algo: "SLB"
enable_bn_calibration: False
quant_type: "W1"
t_start_val: 1.0
t_start_time: 0.4
t_end_time: 0.9
t_factor: 1.12

# Export options
device_id: 0
width: 224
height: 224
file_name: "resnet18"
file_format: "MINDIR"
ckpt_file: ""
network_dataset: "resnet18_imagenet2012"

# Retrain options
save_graphs: False
save_graphs_path: "./graphs"
has_trained_epoch: 0
has_trained_step: 0

# postprocess resnet inference
result_path: ''
label_path: ''

---
# Help description for each configuration
enable_modelarts: "Whether training on modelarts, default: False"
data_url: "Dataset url for obs."
checkpoint_url: "The location of checkpoint for obs."
data_path: "Dataset path for local."
output_path: "Training output path for local."
load_path: "The location of checkpoint for obs."
device_target: "Target device type, available: [Ascend, GPU, CPU]"
enable_profiling: "Whether enable profiling while training, default: False"
num_classes: "Class for dataset."
batch_size: "Batch size for training and evaluation."
epoch_size: "Total training epochs, should be bigger than has_trained_epoch if retrain."
checkpoint_path: "The location of the checkpoint file."
checkpoint_file_path: "The location of the checkpoint file."
save_graphs: "Whether save graphs during training, default: False"
save_graphs_path: "Path to save graphs."
comp_algo: "The quantization algorithm, default: SLB"
enable_act_quant: "Whether apply activation quantization while training, default: False"
enable_bn_calibration: "Whether apply batchnorm calibration while training, default: False"
quant_type: "Quantization bit number of weight and activation, available: [W1, W2, W4, W1A8, W2A8, W4A8]"
t_start_val: "Initial value of temperature hyperparameters, default: 1.0"
t_start_time: "Fraction of epochs after which temperature hyperparameters starting changing, default: 0.2"
t_end_time: "Fraction of epochs after which temperature hyperparameters stopping changing, default: 0.6"
t_factor: "Multiplicative factor of temperature hyperparameters changing, default: 1.2"
