# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: "/mindx-user-12/data/"
train_url: "/mindx-user-12/output/"
checkpoint_url: ""
# Path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path/"
device_target: 'Ascend'
enable_profiling: False

# ==============================================================================s
# Common options
net: "sphereface20a"
dataset: "CASIA-WebFace"
is_distributed: 1
rank: 0
group_size: 1

# ==============================================================================
# Training options
filter_weight: True
label_smooth: 1
smooth_factor: 0.15
train_data_dir: "./dataset/casia_landmark.txt"
train_img_dir : "./dataset/CASIA-WebFace/"
train_pretrained: "sphereface_ascend_v130_casiawebface_official_cv_bs32_acc99.11.ckpt"
model_train_url: ""
image_size: "112, 96"
num_classes: 20000
lr: 0.15
lr_scheduler: "cosine_annealing"
lr_epochs: "1"
lr_gamma: 0.35
eta_min: 0
T_max: 1
max_epoch: 1
per_batch_size: 1
warmup_epochs: 0
weight_decay: 0.0005
momentum: 0.9
is_dynamic_loss_scale: 0
loss_scale: 1024
log_interval: 100
ckpt_interval: 500
save_ckpt_path: "./"
is_save_on_master: 1

# Eval options
eval_data_dir: "./result_Files"
ckpt_files: "./sphereface_ascend_v130_casiawebface_official_cv_bs32_acc99.11.ckpt"
datatxt_src: './lfw//lfw_landmark.txt'
pairtxt_src: './lfw/pairs.txt'
datasrc: './lfw/lfw/'
log_path: ""
eval_url: ""

# export options
device_id: 1
batch_size: 32
file_name: "sphereface"
file_format: 'MINDIR'

---
# Help description for each configuration
enable_modelarts: "if enable_modelarts"
data_url: ""
train_url: ""
checkpoint_url: ""
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path/"
device_target: 'Ascend'
enable_profiling: False
net: "spherenet20a"
dataset: "Dataset, CASIA-WebFace"
is_distributed: "if multi device"
train_data_dir: "train url"
train_pretrained: "model_path, local pretrained model to load"
model_train_url: "model train url"
image_size: "input image sizes"
num_classes: "num_classes"
lr: "lr"
lr_scheduler: "consine_annealing"
lr_epochs: "lr epochs"
ckpt_path: "train ckpt save path"
log_path: "path to save log"
ckpt_files: "fully path of pretrained model to load If it is a direction, it will test all ckpt"
rank: "local rank of distributed"
group size: "world size of distributed"
backbone: "backbone"
device_id: "Device id"
file_name: "output file name"
file_format: "file format choices [AIR MINDIR ONNX]"
