# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: "CPU"
need_modelarts_dataset_unzip: False
modelarts_dataset_unzip_name: ""

# ==============================================================================
# options
batch_size: 16
eval_batch_size: 1
src_vocab_size: 8154
trg_vocab_size: 6113
encoder_embedding_size: 256
decoder_embedding_size: 256
hidden_size: 512
max_length: 32
num_epochs: 13
save_checkpoint: True
ckpt_epoch: 1
target_file: "target.txt"
output_file: "output.txt"
keep_checkpoint_max: 5
base_lr: 0.001
warmup_step: 300
momentum: 0.9
init_loss_scale_value: 1024
scale_factor: 2
scale_window: 2000
warmup_ratio: 0.333333
teacher_force_ratio: 0.5
compute_type: mstype.float16
dtype: mstype.float32

run_distribute: False
dataset_path: ""
pre_trained: ""
ckpt_path: "outputs/"
outputs_dir: "./"
ckpt_file: ""

# export option
file_name: "gru"
file_format: "MINDIR"

# postprocess option
label_dir: ""
result_dir: "./result_Files"

# preprocess option
device_num: 1
result_path: "./preprocess_Result/"

---

# Help description for each configuration
enable_modelarts: "Whether training on modelarts, default: False"
data_url: "Url for modelarts"
train_url: "Url for modelarts"
data_path: "The location of the input data."
output_path: "The location of the output file."
device_target: 'Target device type'

run_distribute: "Run distribute, default: false."
dataset_path: "Dataset path"
pre_trained: "Pretrained file path."
ckpt_path: "Checkpoint save location. Default: outputs/"
outputs_dir: "Checkpoint save location. Default: outputs/"
ckpt_file: "ckpt file path"
# export option
file_name: "output file name."
file_format: "file format. choices in ['AIR', 'MINDIR']"
# postprocess option
label_dir: "label data dir"
result_dir: "infer result Files"
# preprocess option
device_num: "Use device nums, default is 1"
result_path: "result path"